user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "p=9") { return 302 /2020/05/04/example-post-3/; }
            if ($query_string = "page_id=6") { return 302 /blog-2/; }
            if ($query_string = "page_id=7") { return 302 /contact/; }
            if ($query_string = "page_id=8") { return 302 /about/; }
            if ($query_string = "p=10") { return 302 /2020/05/04/example-post-2/; }
            if ($query_string = "p=11") { return 302 /2020/05/04/example-post/; }
        }
    }
}
